/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rental_bayiku.user;



/**
 *
 * @author achmad
 */
public class form_user_utama_1 extends javax.swing.JFrame {

    /**
     * Creates new form form_user_utama_1
     */
    public form_user_utama_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUser = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuMaster = new javax.swing.JMenu();
        jMenuItemBarang = new javax.swing.JMenuItem();
        jMenuItemPeminjam = new javax.swing.JMenuItem();
        jMenuTrans = new javax.swing.JMenu();
        jMenuItemPinjam = new javax.swing.JMenuItem();
        jMenuItemKembali = new javax.swing.JMenuItem();
        jMenuLaporan = new javax.swing.JMenu();
        jMenuLapPin = new javax.swing.JMenuItem();
        jMenuItemLapKem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/welcome-305504_960_720.png"))); // NOI18N

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 50));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 80));

        jMenuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/User_32.png"))); // NOI18N
        jMenuUser.setText("LOGOUT");
        jMenuUser.setPreferredSize(new java.awt.Dimension(100, 70));

        jMenuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/exit-32.png"))); // NOI18N
        jMenuItemExit.setText("EXIT");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuUser.add(jMenuItemExit);

        jMenuBar1.add(jMenuUser);

        jMenuMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/Login-toolbar-32.png"))); // NOI18N
        jMenuMaster.setText("DATA MASTER");
        jMenuMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMasterActionPerformed(evt);
            }
        });

        jMenuItemBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/Checklist-32.png"))); // NOI18N
        jMenuItemBarang.setText("DATA BARANG");
        jMenuItemBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBarangActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemBarang);

        jMenuItemPeminjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/admin.PNG"))); // NOI18N
        jMenuItemPeminjam.setText("DATA PEMINJAM");
        jMenuItemPeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPeminjamActionPerformed(evt);
            }
        });
        jMenuMaster.add(jMenuItemPeminjam);

        jMenuBar1.add(jMenuMaster);

        jMenuTrans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/Shopping-List-Alt-32.png"))); // NOI18N
        jMenuTrans.setText("TRANSAKSI");
        jMenuTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTransActionPerformed(evt);
            }
        });

        jMenuItemPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/spend_intel_black.png"))); // NOI18N
        jMenuItemPinjam.setText("Peminjaman");
        jMenuItemPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPinjamActionPerformed(evt);
            }
        });
        jMenuTrans.add(jMenuItemPinjam);

        jMenuItemKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/arrow-back-1-icon.png"))); // NOI18N
        jMenuItemKembali.setText("Pengembalian ");
        jMenuItemKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKembaliActionPerformed(evt);
            }
        });
        jMenuTrans.add(jMenuItemKembali);

        jMenuBar1.add(jMenuTrans);

        jMenuLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/Checklist-32.png"))); // NOI18N
        jMenuLaporan.setText("LAPORAN ");
        jMenuLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLaporanActionPerformed(evt);
            }
        });

        jMenuLapPin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/Icon_6-512.png"))); // NOI18N
        jMenuLapPin.setText("LAPORAN PEMINJAMAN");
        jMenuLapPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLapPinActionPerformed(evt);
            }
        });
        jMenuLaporan.add(jMenuLapPin);

        jMenuItemLapKem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/si_pergudangan/image/Icon_6-512.png"))); // NOI18N
        jMenuItemLapKem.setText("LAPORAN PENGEMBALIAN");
        jMenuItemLapKem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLapKemActionPerformed(evt);
            }
        });
        jMenuLaporan.add(jMenuItemLapKem);

        jMenuBar1.add(jMenuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuMasterActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jMenuMasterActionPerformed

    private void jMenuItemPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPinjamActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new akses_peminjaman_1().setVisible(true);
    }//GEN-LAST:event_jMenuItemPinjamActionPerformed

    private void jMenuItemKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKembaliActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new form_user_kembali1_1().setVisible(true);
    }//GEN-LAST:event_jMenuItemKembaliActionPerformed

    private void jMenuLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLaporanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuLaporanActionPerformed

    private void jMenuItemBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBarangActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new form_user_barang().setVisible(true);
    }//GEN-LAST:event_jMenuItemBarangActionPerformed

    private void jMenuLapPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLapPinActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new si_pergudangan.report.cetak_pinjam().setVisible(true);
    }//GEN-LAST:event_jMenuLapPinActionPerformed

    private void jMenuItemPeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeminjamActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new rental_bayiku.user.form_user_dataPeminjam().setVisible(true);
    }//GEN-LAST:event_jMenuItemPeminjamActionPerformed

    private void jMenuTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTransActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenuTransActionPerformed

    private void jMenuItemLapKemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLapKemActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new si_pergudangan.report.cetak_kembali().setVisible(true);
    }//GEN-LAST:event_jMenuItemLapKemActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_user_utama_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_user_utama_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_user_utama_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_user_utama_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_user_utama_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemBarang;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemKembali;
    private javax.swing.JMenuItem jMenuItemLapKem;
    private javax.swing.JMenuItem jMenuItemPeminjam;
    private javax.swing.JMenuItem jMenuItemPinjam;
    private javax.swing.JMenuItem jMenuLapPin;
    private javax.swing.JMenu jMenuLaporan;
    private javax.swing.JMenu jMenuMaster;
    private javax.swing.JMenu jMenuTrans;
    private javax.swing.JMenu jMenuUser;
    // End of variables declaration//GEN-END:variables
}
